In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pydot
import graphviz
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("iris_data.csv")
dataset.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [3]:
X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [4]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
model = Sequential()
model.add(Dense(4,input_shape=(4,), activation='relu'))
model.add(Dense(3, activation='softmax'))

In [6]:
model.compile(optimizer="Adam", loss='categorical_crossentropy', metrics=['accuracy'])

In [7]:
model.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
12/12 [==============================] - 0s 1ms/step - loss: 0.6268 - accuracy: 0.6639
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 0.6040 - accuracy: 0.6387
Epoch 3/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5903 - accuracy: 0.5882
Epoch 4/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5840 - accuracy: 0.5798
Epoch 5/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5777 - accuracy: 0.5714
Epoch 6/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5717 - accuracy: 0.5966
Epoch 7/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5659 - accuracy: 0.6050
Epoch 8/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5595 - accuracy: 0.6050
Epoch 9/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5535 - accuracy: 0.6050
Epoch 10/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5478 - accuracy: 0.6303
Epoch 11/

12/12 [==============================] - 0s 1ms/step - loss: 0.2597 - accuracy: 0.9748
Epoch 84/100
12/12 [==============================] - 0s 2ms/step - loss: 0.2571 - accuracy: 0.9580
Epoch 85/100
12/12 [==============================] - 0s 1ms/step - loss: 0.2535 - accuracy: 0.9664
Epoch 86/100
12/12 [==============================] - 0s 1ms/step - loss: 0.2515 - accuracy: 0.9748
Epoch 87/100
12/12 [==============================] - 0s 1ms/step - loss: 0.2488 - accuracy: 0.9748
Epoch 88/100
12/12 [==============================] - 0s 1ms/step - loss: 0.2470 - accuracy: 0.9748
Epoch 89/100
12/12 [==============================] - 0s 1ms/step - loss: 0.2450 - accuracy: 0.9748
Epoch 90/100
12/12 [==============================] - 0s 2ms/step - loss: 0.2429 - accuracy: 0.9748
Epoch 91/100
12/12 [==============================] - 0s 1ms/step - loss: 0.2407 - accuracy: 0.9580
Epoch 92/100
12/12 [==============================] - 0s 1ms/step - loss: 0.2391 - accuracy: 0.9664
Epoch 93/100


In [8]:
y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

1/1 [==============================] - 0s 76ms/step


In [9]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[12  0  0]
 [ 0 10  0]
 [ 0  0  8]]
