In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pydot
import graphviz
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("iris_data.csv")
dataset.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [3]:
X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [4]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
model = Sequential()
model.add(Dense(4,input_shape=(4,), activation='relu'))
model.add(Dense(3, activation='softmax'))

In [6]:
model.compile(optimizer="Adam", loss='categorical_crossentropy', metrics=['accuracy'])

In [8]:
model.fit(X_train, y_train, batch_size=10, epochs=150)

Epoch 1/150
12/12 [==============================] - 0s 2ms/step - loss: 0.5114 - accuracy: 0.6639
Epoch 2/150
12/12 [==============================] - 0s 2ms/step - loss: 0.5106 - accuracy: 0.6639
Epoch 3/150
12/12 [==============================] - 0s 2ms/step - loss: 0.5091 - accuracy: 0.6639
Epoch 4/150
12/12 [==============================] - 0s 2ms/step - loss: 0.5085 - accuracy: 0.6639
Epoch 5/150
12/12 [==============================] - 0s 2ms/step - loss: 0.5074 - accuracy: 0.6639
Epoch 6/150
12/12 [==============================] - 0s 2ms/step - loss: 0.5067 - accuracy: 0.6639
Epoch 7/150
12/12 [==============================] - 0s 2ms/step - loss: 0.5062 - accuracy: 0.6639
Epoch 8/150
12/12 [==============================] - 0s 2ms/step - loss: 0.5060 - accuracy: 0.6639
Epoch 9/150
12/12 [==============================] - 0s 2ms/step - loss: 0.5054 - accuracy: 0.6639
Epoch 10/150
12/12 [==============================] - 0s 2ms/step - loss: 0.5037 - accuracy: 0.6639
Epoch 11/

12/12 [==============================] - 0s 1ms/step - loss: 0.4689 - accuracy: 0.6807
Epoch 84/150
12/12 [==============================] - 0s 1ms/step - loss: 0.4699 - accuracy: 0.6723
Epoch 85/150
12/12 [==============================] - 0s 1ms/step - loss: 0.4703 - accuracy: 0.6639
Epoch 86/150
12/12 [==============================] - 0s 1ms/step - loss: 0.4672 - accuracy: 0.6639
Epoch 87/150
12/12 [==============================] - 0s 1ms/step - loss: 0.4671 - accuracy: 0.6639
Epoch 88/150
12/12 [==============================] - 0s 1ms/step - loss: 0.4670 - accuracy: 0.6639
Epoch 89/150
12/12 [==============================] - 0s 1ms/step - loss: 0.4663 - accuracy: 0.6639
Epoch 90/150
12/12 [==============================] - 0s 1ms/step - loss: 0.4666 - accuracy: 0.6975
Epoch 91/150
12/12 [==============================] - 0s 1ms/step - loss: 0.4657 - accuracy: 0.6723
Epoch 92/150
12/12 [==============================] - 0s 1ms/step - loss: 0.4658 - accuracy: 0.6639
Epoch 93/150


In [9]:
y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

1/1 [==============================] - 0s 107ms/step


In [10]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.60      0.30      0.40        10
           2       0.46      0.75      0.57         8

    accuracy                           0.70        30
   macro avg       0.69      0.68      0.66        30
weighted avg       0.72      0.70      0.69        30

[[12  0  0]
 [ 0  3  7]
 [ 0  2  6]]
