In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pydot
import graphviz
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("iris_data.csv")
dataset.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [3]:
X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [4]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
model = Sequential()
model.add(Dense(4,input_shape=(4,), activation='relu'))
model.add(Dense(3, activation='softmax'))

In [6]:
model.compile(optimizer="Adam", loss='categorical_crossentropy', metrics=['accuracy'])

In [7]:
model.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
12/12 [==============================] - 0s 1ms/step - loss: 1.3562 - accuracy: 0.3529
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 1.2890 - accuracy: 0.3529
Epoch 3/100
12/12 [==============================] - 0s 1ms/step - loss: 1.2340 - accuracy: 0.3529
Epoch 4/100
12/12 [==============================] - 0s 1ms/step - loss: 1.1840 - accuracy: 0.3529
Epoch 5/100
12/12 [==============================] - 0s 1ms/step - loss: 1.1445 - accuracy: 0.3529
Epoch 6/100
12/12 [==============================] - 0s 1ms/step - loss: 1.1089 - accuracy: 0.3529
Epoch 7/100
12/12 [==============================] - 0s 1ms/step - loss: 1.0819 - accuracy: 0.3529
Epoch 8/100
12/12 [==============================] - 0s 1ms/step - loss: 1.0596 - accuracy: 0.3529
Epoch 9/100
12/12 [==============================] - 0s 1ms/step - loss: 1.0390 - accuracy: 0.3529
Epoch 10/100
12/12 [==============================] - 0s 1ms/step - loss: 1.0241 - accuracy: 0.3529
Epoch 11/

Epoch 83/100
12/12 [==============================] - 0s 1ms/step - loss: 0.6459 - accuracy: 0.6723
Epoch 84/100
12/12 [==============================] - 0s 1ms/step - loss: 0.6432 - accuracy: 0.6723
Epoch 85/100
12/12 [==============================] - 0s 1ms/step - loss: 0.6405 - accuracy: 0.6723
Epoch 86/100
12/12 [==============================] - 0s 1ms/step - loss: 0.6381 - accuracy: 0.6975
Epoch 87/100
12/12 [==============================] - 0s 1ms/step - loss: 0.6352 - accuracy: 0.6975
Epoch 88/100
12/12 [==============================] - 0s 1ms/step - loss: 0.6327 - accuracy: 0.6975
Epoch 89/100
12/12 [==============================] - 0s 1ms/step - loss: 0.6304 - accuracy: 0.6975
Epoch 90/100
12/12 [==============================] - 0s 1ms/step - loss: 0.6278 - accuracy: 0.6975
Epoch 91/100
12/12 [==============================] - 0s 1ms/step - loss: 0.6252 - accuracy: 0.6975
Epoch 92/100
12/12 [==============================] - 0s 1ms/step - loss: 0.6228 - accuracy: 0.6975


In [8]:
y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

1/1 [==============================] - 0s 74ms/step


In [9]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.10      0.18        10
           2       0.47      1.00      0.64         8

    accuracy                           0.70        30
   macro avg       0.82      0.70      0.61        30
weighted avg       0.86      0.70      0.63        30

[[12  0  0]
 [ 0  1  9]
 [ 0  0  8]]
