In [2]:
#pip install opencv-python
import cv2
import numpy as np
import pandas as pd

In [2]:
img=cv2.imread('noidea.jpg')
cv2.imshow('Images',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
img_grey=cv2.imread('noidea.jpg',0)
img_rgb=cv2.imread('noidea.jpg',1)
cv2.imshow('Images_grey',img_grey)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(img_grey.shape)

(414, 625)


In [4]:
print(img_grey)

[[131 131 131 ... 143 143 144]
 [132 131 131 ... 143 143 144]
 [132 132 132 ... 144 144 144]
 ...
 [175 174 175 ... 145  35  23]
 [173 171 171 ...  14  24  26]
 [170 167 168 ...  25  19  21]]


In [5]:
img=cv2.imread('noidea.jpg')
img=cv2.resize(img,(300,200))
cv2.imshow('Original Images',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
img.shape

(200, 300, 3)

In [7]:
img=cv2.imread('noidea.jpg')
img=cv2.resize(img,(300,200))
img_2=np.hstack((img,img))
cv2.imshow('Original Images',img_2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
img=cv2.imread('noidea.jpg')
img=cv2.resize(img,(300,200))
img_2=np.hstack((img,img))
img_4=np.vstack((img_2,img_2))
cv2.imshow('Original Images',img_4)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Video Workout

In [4]:
import cv2
import numpy as np
import pandas as pd
video=cv2.VideoCapture('O Antava.mp4')
while video.isOpened():
    ret,frame=video.read()
    if ret:
        video1=cv2.resize(frame,(800,600))
        cv2.imshow("Video Player",video1)
        
        if cv2.waitKey(25) & 0xff==ord('q'):
            break
    else:
        break
video.release()
cv2.destroyAllWindows()

In [5]:
#import cv2
#import numpy as np
#import pandas as pd
video=cv2.VideoCapture('O Antava.mp4')
while video.isOpened():
    ret,frame=video.read()
    if ret:
        video1=cv2.resize(frame,(400,300))
        video2=np.hstack((video1,video1))
        cv2.imshow("Video Player",video2)
        
        if cv2.waitKey(25) & 0xff==ord('q'):
            break
    else:
        break
video.release()
cv2.destroyAllWindows()

In [7]:
video=cv2.VideoCapture('Waka Waka.mp4')
while video.isOpened():
    ret,frame=video.read()
    if ret:
        video1=cv2.resize(frame,(400,300))
        video2=np.hstack((video1,video1))
        video4=np.vstack((video2,video2))
        cv2.imshow("Video Player",video4)
        
        if cv2.waitKey(25) & 0xff==ord('q'):
            break
    else:
        break
video.release()
cv2.destroyAllWindows()

# System Camera

In [8]:
video=cv2.VideoCapture(0)
while video.isOpened():
    ret,frame=video.read()
    if ret:
        video1=cv2.resize(frame,(400,300))
        #video2=np.hstack((video1,video1))
        #video4=np.vstack((video2,video2))
        cv2.imshow("Video Player",video1)
        
        if cv2.waitKey(25) & 0xff==ord('q'):
            break
    else:
        break
video.release()
cv2.destroyAllWindows()

In [9]:
video=cv2.VideoCapture(0)
while video.isOpened():
    ret,frame=video.read()
    if ret:
        video1=cv2.resize(frame,(400,300))
        video2=np.hstack((video1,video1))
        video4=np.vstack((video2,video2))
        cv2.imshow("Video Player",video4)
        
        if cv2.waitKey(25) & 0xff==ord('q'):
            break
    else:
        break
video.release()
cv2.destroyAllWindows()

In [3]:
camera_view=cv2.VideoCapture(0)
video=cv2.VideoCapture("Waka Waka.mp4")
video2=cv2.VideoCapture('Champion (Official Song).mp4')
#video3=cv2.imread('noidea.jpg')
while camera_view.isOpened():
    ret1,frame1=camera_view.read()
    ret2,frame2=video.read()
    ret3,frame3=video2.read()
    if ret1:
        frame1=cv2.resize(frame1,(400,200))
        frame2=cv2.resize(frame2,(400,200))
        frame3=cv2.resize(frame3,(400,200))
        img=cv2.imread('noidea.jpg')
        img=cv2.resize(img,(400,00))
        
        frame_2=np.hstack((frame1,frame2))
        frame_22=np.hstack((frame3,img))
        frame_4=np.vstack((frame_2,frame_22))
        cv2.imshow("Video Player",frame_4)
        
        if cv2.waitKey(25) & 0xff==ord('q'):
            break
    else:
        break
camera_view.release()
cv2.destroyAllWindows()

In [12]:
import os
os.mkdir("video_to_img")
video=cv2.VideoCapture('Waka Waka.mp4')
img_count=1

while video.isOpened():
    ret,frame=video.read()
    
    if not ret:
        print("no frames available")
        break
    is_img_write=cv2.imwrite(f"video_to_img\img{img_count}.jpeg",frame)
    
    if is_img_write:
        print(f'img has been saved at video_to_img\img{img_count}.jpeg')
    cv2.imshow("video",frame)
    
    cv2.waitKey(25) & 0xff==ord('q')
    img_count +=1
    
    if img_count>30:
        break
    
video.release()
cv2.destroyAllWindows()

img has been saved at video_to_img\img1.jpeg
img has been saved at video_to_img\img2.jpeg
img has been saved at video_to_img\img3.jpeg
img has been saved at video_to_img\img4.jpeg
img has been saved at video_to_img\img5.jpeg
img has been saved at video_to_img\img6.jpeg
img has been saved at video_to_img\img7.jpeg
img has been saved at video_to_img\img8.jpeg
img has been saved at video_to_img\img9.jpeg
img has been saved at video_to_img\img10.jpeg
img has been saved at video_to_img\img11.jpeg
img has been saved at video_to_img\img12.jpeg
img has been saved at video_to_img\img13.jpeg
img has been saved at video_to_img\img14.jpeg
img has been saved at video_to_img\img15.jpeg
img has been saved at video_to_img\img16.jpeg
img has been saved at video_to_img\img17.jpeg
img has been saved at video_to_img\img18.jpeg
img has been saved at video_to_img\img19.jpeg
img has been saved at video_to_img\img20.jpeg
img has been saved at video_to_img\img21.jpeg
img has been saved at video_to_img\img22.jp