In [11]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import seaborn as sns
import pandas as pd
import numpy as np

In [12]:
dataset = pd.read_csv("iris_data.csv")
dataset.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [13]:
X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [14]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
model = Sequential()
model.add(Dense(4,input_shape=(4,), activation='relu'))
model.add(Dense(3, activation='softmax'))

In [16]:
model.compile(optimizer="Adam", loss='categorical_crossentropy', metrics=['accuracy'])

In [17]:
model.fit(X_train, y_train, batch_size=10, epochs=150)

Epoch 1/150
12/12 [==============================] - 0s 1ms/step - loss: 1.3748 - accuracy: 0.3529
Epoch 2/150
12/12 [==============================] - 0s 1ms/step - loss: 1.2851 - accuracy: 0.3529
Epoch 3/150
12/12 [==============================] - 0s 1ms/step - loss: 1.2202 - accuracy: 0.3529
Epoch 4/150
12/12 [==============================] - 0s 1ms/step - loss: 1.1828 - accuracy: 0.3529
Epoch 5/150
12/12 [==============================] - 0s 2ms/step - loss: 1.1573 - accuracy: 0.3529
Epoch 6/150
12/12 [==============================] - 0s 1ms/step - loss: 1.1373 - accuracy: 0.3529
Epoch 7/150
12/12 [==============================] - 0s 1ms/step - loss: 1.1170 - accuracy: 0.3529
Epoch 8/150
12/12 [==============================] - 0s 1ms/step - loss: 1.0974 - accuracy: 0.3529
Epoch 9/150
12/12 [==============================] - 0s 1ms/step - loss: 1.0778 - accuracy: 0.3529
Epoch 10/150
12/12 [==============================] - 0s 2ms/step - loss: 1.0616 - accuracy: 0.3529
Epoch 11/

12/12 [==============================] - 0s 1ms/step - loss: 0.5811 - accuracy: 0.8487
Epoch 84/150
12/12 [==============================] - 0s 1ms/step - loss: 0.5778 - accuracy: 0.8655
Epoch 85/150
12/12 [==============================] - 0s 1ms/step - loss: 0.5743 - accuracy: 0.8655
Epoch 86/150
12/12 [==============================] - 0s 1ms/step - loss: 0.5715 - accuracy: 0.8824
Epoch 87/150
12/12 [==============================] - 0s 1ms/step - loss: 0.5675 - accuracy: 0.8908
Epoch 88/150
12/12 [==============================] - 0s 909us/step - loss: 0.5647 - accuracy: 0.8739
Epoch 89/150
12/12 [==============================] - 0s 1ms/step - loss: 0.5611 - accuracy: 0.8655
Epoch 90/150
12/12 [==============================] - 0s 1ms/step - loss: 0.5588 - accuracy: 0.8824
Epoch 91/150
12/12 [==============================] - 0s 1ms/step - loss: 0.5547 - accuracy: 0.8908
Epoch 92/150
12/12 [==============================] - 0s 1ms/step - loss: 0.5516 - accuracy: 0.8824
Epoch 93/15

In [18]:
y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

1/1 [==============================] - 0s 42ms/step


In [19]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.75      0.90      0.82        10
           2       0.83      0.62      0.71         8

    accuracy                           0.87        30
   macro avg       0.86      0.84      0.84        30
weighted avg       0.87      0.87      0.86        30

[[12  0  0]
 [ 0  9  1]
 [ 0  3  5]]
